kind: Job
apiVersion: batch/v1
metadata:
  name: whisper-transcription-tiny-das-{{.JobName}}-{{.Iteration}}-{{.Replica}}
  labels:
    group: whisper-tiny
spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  ttlSecondsAfterFinished: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: whisper-transcriber-das
        image: quay.io/smalleni/whisper:latest
        imagePullPolicy: Always
        # Command to download audio file and then run whisper
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Running download script..."
          /scripts/download-audio.sh
          FILE=$(ls /data/* | head -n 1)
          echo "Running whisper transcription..."
          whisper "$FILE" --model_dir /tmp/whisper_models --model tiny.en --output_dir /tmp
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
        - name: ITERATION
          value: "{{.Iteration}}"
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            memory: "4Gi"
{{ if .das }}
            nvidia.com/mig-1g.5gb: 1
{{ else }}
            nvidia.com/gpu: 1
{{ end}}
        volumeMounts:
        - name: audio-data
          mountPath: /data
        - name: model-cache-volume
          mountPath: /tmp/whisper_models
        - name: download-script
          mountPath: /scripts
      volumes:
      - name: audio-data
        emptyDir: {} # An ephemeral volume to share data between containers
      - name: model-cache-volume
        emptyDir: {}
      - name: download-script
        configMap:
          name: audio-download-script
          defaultMode: 0755 # Make the script executable
