# cluster-queue.yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # An empty selector allows all namespaces to use this ClusterQueue.
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources: ["nvidia.com/gpu"]
    flavors:
    - name: "gpu-flavor"
      resources:
      - name: "nvidia.com/gpu"
        nominalQuota: 1
